name: TALENTNEPAL
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
title: 'BLOCKCHAIN DEVELOPERS REQUIRED '
author: {}
color:
  lightness: 0.750472495041432
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  saturation: 0.8758828199645231
  brandStrength: 0.1929135048279803
  rhythmicContrast: 0.3500718684750777
